"""baseline_mysql

Revision ID: 133877812708
Revises: 
Create Date: 2026-09-07 17:16:27.385565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133877812708'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correos_pendientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destinatario_email', sa.String(length=255), nullable=False),
    sa.Column('asunto', sa.String(length=255), nullable=False),
    sa.Column('cuerpo_texto', sa.Text(), nullable=False),
    sa.Column('enviado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_enviado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correos_pendientes_enviado'), 'correos_pendientes', ['enviado'], unique=False)
    op.create_index(op.f('ix_correos_pendientes_id'), 'correos_pendientes', ['id'], unique=False)
    op.create_table('eventos_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('cumpleanos', 'festivo', 'evento', name='tipoeventoempresa'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'tipo', name='uq_evento_empresa_nombre_tipo')
    )
    op.create_index(op.f('ix_eventos_empresa_id'), 'eventos_empresa', ['id'], unique=False)
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyectos_id'), 'proyectos', ['id'], unique=False)
    op.create_index(op.f('ix_proyectos_parent_id'), 'proyectos', ['parent_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('puesto', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('es_super_admin', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('aviso_acceso_enviado', sa.Boolean(), nullable=False),
    sa.Column('telefono_whatsapp', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('entregables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=False),
    sa.Column('hora_entrega', sa.Time(), nullable=True),
    sa.Column('porcentaje_avance', sa.Integer(), nullable=False),
    sa.Column('estatus', sa.Enum('pendiente', 'en_progreso', 'pendiente_aprobacion', 'cumplido', name='estatusentregable'), nullable=False),
    sa.Column('sensible', sa.Boolean(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('urgente_manual', sa.Boolean(), nullable=False),
    sa.Column('requiere_comprobante', sa.Boolean(), nullable=False),
    sa.Column('comprobante_path', sa.String(length=300), nullable=True),
    sa.Column('avance_previo_aprobacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entregables_id'), 'entregables', ['id'], unique=False)
    op.create_table('equipo_miembros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propietario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('N1', 'N2', 'N3', 'N4', name='rolenum'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['propietario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('propietario_id', 'usuario_id', name='uq_equipo_propietario_usuario')
    )
    op.create_index(op.f('ix_equipo_miembros_id'), 'equipo_miembros', ['id'], unique=False)
    op.create_table('pendientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=500), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pendientes_id'), 'pendientes', ['id'], unique=False)
    op.create_table('pendientes_personales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=500), nullable=False),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('hora_limite', sa.Time(), nullable=True),
    sa.Column('hecho', sa.Boolean(), nullable=False),
    sa.Column('recurrencia', sa.String(length=10), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pendientes_personales_id'), 'pendientes_personales', ['id'], unique=False)
    op.create_table('preferencias_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('card_order', sa.JSON(), nullable=True),
    sa.Column('tarjetas_ocultas', sa.JSON(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_preferencias_usuario_id'), 'preferencias_usuario', ['id'], unique=False)
    op.create_table('series_reunion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('organizador_id', sa.Integer(), nullable=False),
    sa.Column('tipo_recurrencia', sa.Enum('diaria', 'semanal', 'mensual', name='tiporecurrencia'), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=True),
    sa.Column('dia_mes', sa.Integer(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('recordatorio_minutos_antes', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organizador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_reunion_id'), 'series_reunion', ['id'], unique=False)
    op.create_table('suscripciones_push',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suscripciones_push_endpoint'), 'suscripciones_push', ['endpoint'], unique=True)
    op.create_index(op.f('ix_suscripciones_push_id'), 'suscripciones_push', ['id'], unique=False)
    op.create_table('usuario_proyecto_rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('N1', 'N2', 'N3', 'N4', name='rolenum'), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'proyecto_id', name='uq_usuario_proyecto')
    )
    op.create_index(op.f('ix_usuario_proyecto_rol_id'), 'usuario_proyecto_rol', ['id'], unique=False)
    op.create_table('historial_avance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entregable_id', sa.Integer(), nullable=False),
    sa.Column('porcentaje_avance', sa.Integer(), nullable=False),
    sa.Column('actualizado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['entregable_id'], ['entregables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_avance_id'), 'historial_avance', ['id'], unique=False)
    op.create_table('historial_responsable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entregable_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_desde', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entregable_id'], ['entregables.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_responsable_entregable_id'), 'historial_responsable', ['entregable_id'], unique=False)
    op.create_index(op.f('ix_historial_responsable_id'), 'historial_responsable', ['id'], unique=False)
    op.create_index(op.f('ix_historial_responsable_usuario_id'), 'historial_responsable', ['usuario_id'], unique=False)
    op.create_table('reuniones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('recordatorio_minutos_antes', sa.Integer(), nullable=True),
    sa.Column('organizador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['serie_id'], ['series_reunion.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reuniones_id'), 'reuniones', ['id'], unique=False)
    op.create_table('serie_reunion_participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['serie_id'], ['series_reunion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serie_reunion_participantes_id'), 'serie_reunion_participantes', ['id'], unique=False)
    op.create_table('minutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reunion_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reunion_id'], ['reuniones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reunion_id')
    )
    op.create_index(op.f('ix_minutas_id'), 'minutas', ['id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('entregable_id', sa.Integer(), nullable=True),
    sa.Column('evento_empresa_id', sa.Integer(), nullable=True),
    sa.Column('reunion_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('recordatorio_proximo', 'recordatorio_vencido', 'entregable_asignado', 'avance_actualizado', 'reunion_hoy', 'recordatorio_reunion', 'otro', name='tiponotificacion'), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('urgente', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entregable_id'], ['entregables.id'], ),
    sa.ForeignKeyConstraint(['evento_empresa_id'], ['eventos_empresa.id'], ),
    sa.ForeignKeyConstraint(['reunion_id'], ['reuniones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_table('reunion_participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reunion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('asistio', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reunion_id'], ['reuniones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reunion_participantes_id'), 'reunion_participantes', ['id'], unique=False)
    op.create_table('acuerdos_minuta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minuta_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('entregable_id', sa.Integer(), nullable=True),
    sa.Column('convertido', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entregable_id'], ['entregables.id'], ),
    sa.ForeignKeyConstraint(['minuta_id'], ['minutas.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acuerdos_minuta_id'), 'acuerdos_minuta', ['id'], unique=False)
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entregable_id', sa.Integer(), nullable=True),
    sa.Column('reunion_id', sa.Integer(), nullable=True),
    sa.Column('minuta_id', sa.Integer(), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('nota_padre_id', sa.Integer(), nullable=True),
    sa.Column('pendiente_padre_id', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('imagen_path', sa.String(length=300), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(CASE WHEN entregable_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN reunion_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN minuta_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN proyecto_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN nota_padre_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN pendiente_padre_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_nota_exactamente_un_padre'),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['entregable_id'], ['entregables.id'], ),
    sa.ForeignKeyConstraint(['minuta_id'], ['minutas.id'], ),
    sa.ForeignKeyConstraint(['nota_padre_id'], ['notas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pendiente_padre_id'], ['pendientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['reunion_id'], ['reuniones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_id'), 'notas', ['id'], unique=False)
    op.create_table('agenda_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.Column('reunion_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('tema', 'entregable', 'acuerdo', 'pendiente', 'nota', name='tipoagendaitem'), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('entregable_id', sa.Integer(), nullable=True),
    sa.Column('acuerdo_id', sa.Integer(), nullable=True),
    sa.Column('nota_id', sa.Integer(), nullable=True),
    sa.Column('pendiente_id', sa.Integer(), nullable=True),
    sa.Column('seccion_proyecto_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.String(length=500), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en_reunion_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(CASE WHEN serie_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN reunion_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_agenda_item_serie_o_reunion'),
    sa.ForeignKeyConstraint(['acuerdo_id'], ['acuerdos_minuta.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_en_reunion_id'], ['reuniones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entregable_id'], ['entregables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nota_id'], ['notas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pendiente_id'], ['pendientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reunion_id'], ['reuniones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seccion_proyecto_id'], ['proyectos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['serie_id'], ['series_reunion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_items_id'), 'agenda_items', ['id'], unique=False)
    op.create_table('agenda_item_revisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agenda_item_id', sa.Integer(), nullable=False),
    sa.Column('reunion_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('revisado', 'pendiente', 'revisado_con_pendientes', name='estadorevision'), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['agenda_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reunion_id'], ['reuniones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_item_revisiones_id'), 'agenda_item_revisiones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agenda_item_revisiones_id'), table_name='agenda_item_revisiones')
    op.drop_table('agenda_item_revisiones')
    op.drop_index(op.f('ix_agenda_items_id'), table_name='agenda_items')
    op.drop_table('agenda_items')
    op.drop_index(op.f('ix_notas_id'), table_name='notas')
    op.drop_table('notas')
    op.drop_index(op.f('ix_acuerdos_minuta_id'), table_name='acuerdos_minuta')
    op.drop_table('acuerdos_minuta')
    op.drop_index(op.f('ix_reunion_participantes_id'), table_name='reunion_participantes')
    op.drop_table('reunion_participantes')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_minutas_id'), table_name='minutas')
    op.drop_table('minutas')
    op.drop_index(op.f('ix_serie_reunion_participantes_id'), table_name='serie_reunion_participantes')
    op.drop_table('serie_reunion_participantes')
    op.drop_index(op.f('ix_reuniones_id'), table_name='reuniones')
    op.drop_table('reuniones')
    op.drop_index(op.f('ix_historial_responsable_usuario_id'), table_name='historial_responsable')
    op.drop_index(op.f('ix_historial_responsable_id'), table_name='historial_responsable')
    op.drop_index(op.f('ix_historial_responsable_entregable_id'), table_name='historial_responsable')
    op.drop_table('historial_responsable')
    op.drop_index(op.f('ix_historial_avance_id'), table_name='historial_avance')
    op.drop_table('historial_avance')
    op.drop_index(op.f('ix_usuario_proyecto_rol_id'), table_name='usuario_proyecto_rol')
    op.drop_table('usuario_proyecto_rol')
    op.drop_index(op.f('ix_suscripciones_push_id'), table_name='suscripciones_push')
    op.drop_index(op.f('ix_suscripciones_push_endpoint'), table_name='suscripciones_push')
    op.drop_table('suscripciones_push')
    op.drop_index(op.f('ix_series_reunion_id'), table_name='series_reunion')
    op.drop_table('series_reunion')
    op.drop_index(op.f('ix_preferencias_usuario_id'), table_name='preferencias_usuario')
    op.drop_table('preferencias_usuario')
    op.drop_index(op.f('ix_pendientes_personales_id'), table_name='pendientes_personales')
    op.drop_table('pendientes_personales')
    op.drop_index(op.f('ix_pendientes_id'), table_name='pendientes')
    op.drop_table('pendientes')
    op.drop_index(op.f('ix_equipo_miembros_id'), table_name='equipo_miembros')
    op.drop_table('equipo_miembros')
    op.drop_index(op.f('ix_entregables_id'), table_name='entregables')
    op.drop_table('entregables')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_proyectos_parent_id'), table_name='proyectos')
    op.drop_index(op.f('ix_proyectos_id'), table_name='proyectos')
    op.drop_table('proyectos')
    op.drop_index(op.f('ix_eventos_empresa_id'), table_name='eventos_empresa')
    op.drop_table('eventos_empresa')
    op.drop_index(op.f('ix_correos_pendientes_id'), table_name='correos_pendientes')
    op.drop_index(op.f('ix_correos_pendientes_enviado'), table_name='correos_pendientes')
    op.drop_table('correos_pendientes')
    # ### end Alembic commands ###
