"""fase2_3_ondelete_fks

Revision ID: 08f319b66df4
Revises: e956837b9aa5
Create Date: 2026-08-17 14:33:14.536999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f319b66df4'
down_revision: Union[str, None] = 'e956837b9aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agenda_item_revisiones_reunion_id_fkey', 'agenda_item_revisiones', type_='foreignkey')
    op.drop_constraint('agenda_item_revisiones_agenda_item_id_fkey', 'agenda_item_revisiones', type_='foreignkey')
    op.create_foreign_key(None, 'agenda_item_revisiones', 'agenda_items', ['agenda_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agenda_item_revisiones', 'reuniones', ['reunion_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('agenda_items_proyecto_id_fkey', 'agenda_items', type_='foreignkey')
    op.drop_constraint('agenda_items_entregable_id_fkey', 'agenda_items', type_='foreignkey')
    op.drop_constraint('agenda_items_acuerdo_id_fkey', 'agenda_items', type_='foreignkey')
    op.drop_constraint('agenda_items_creado_en_reunion_id_fkey', 'agenda_items', type_='foreignkey')
    op.create_foreign_key(None, 'agenda_items', 'entregables', ['entregable_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'agenda_items', 'acuerdos_minuta', ['acuerdo_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'agenda_items', 'reuniones', ['creado_en_reunion_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'agenda_items', 'proyectos', ['proyecto_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('reuniones_serie_id_fkey', 'reuniones', type_='foreignkey')
    op.create_foreign_key(None, 'reuniones', 'series_reunion', ['serie_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reuniones', type_='foreignkey')
    op.create_foreign_key('reuniones_serie_id_fkey', 'reuniones', 'series_reunion', ['serie_id'], ['id'])
    op.drop_constraint(None, 'agenda_items', type_='foreignkey')
    op.drop_constraint(None, 'agenda_items', type_='foreignkey')
    op.drop_constraint(None, 'agenda_items', type_='foreignkey')
    op.drop_constraint(None, 'agenda_items', type_='foreignkey')
    op.create_foreign_key('agenda_items_creado_en_reunion_id_fkey', 'agenda_items', 'reuniones', ['creado_en_reunion_id'], ['id'])
    op.create_foreign_key('agenda_items_acuerdo_id_fkey', 'agenda_items', 'acuerdos_minuta', ['acuerdo_id'], ['id'])
    op.create_foreign_key('agenda_items_entregable_id_fkey', 'agenda_items', 'entregables', ['entregable_id'], ['id'])
    op.create_foreign_key('agenda_items_proyecto_id_fkey', 'agenda_items', 'proyectos', ['proyecto_id'], ['id'])
    op.drop_constraint(None, 'agenda_item_revisiones', type_='foreignkey')
    op.drop_constraint(None, 'agenda_item_revisiones', type_='foreignkey')
    op.create_foreign_key('agenda_item_revisiones_agenda_item_id_fkey', 'agenda_item_revisiones', 'agenda_items', ['agenda_item_id'], ['id'])
    op.create_foreign_key('agenda_item_revisiones_reunion_id_fkey', 'agenda_item_revisiones', 'reuniones', ['reunion_id'], ['id'])
    # ### end Alembic commands ###
