"""agregar_asistencia_reunion_participante

Revision ID: 12e81284f2ec
Revises: 22bc8cbbf2d5
Create Date: 2026-08-27 15:06:40.353073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e81284f2ec'
down_revision: Union[str, None] = '22bc8cbbf2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reunion_participantes', sa.Column('asistio', sa.Boolean(), nullable=True))
    # NOTA: se quito un drop de constraint no relacionado (drift preexistente).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reunion_participantes', 'asistio')
    # ### end Alembic commands ###
