"""correos alternos por usuario

Revision ID: 14d7abb3c7fa
Revises: c02b12b1b486
Create Date: 2026-09-17 14:15:36.778443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d7abb3c7fa'
down_revision: Union[str, None] = 'c02b12b1b486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correos_alternos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correos_alternos_email'), 'correos_alternos', ['email'], unique=True)
    op.create_index(op.f('ix_correos_alternos_id'), 'correos_alternos', ['id'], unique=False)
    # Nota: se quitó del autogenerate un drop_constraint de
    # 'suscripciones_push_endpoint_key' detectado como drift preexistente
    # en la BD, sin relación con este cambio -- no se toca aquí.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correos_alternos_id'), table_name='correos_alternos')
    op.drop_index(op.f('ix_correos_alternos_email'), table_name='correos_alternos')
    op.drop_table('correos_alternos')
    # ### end Alembic commands ###
