"""tarjetas ocultas en preferencias de usuario

Revision ID: 1b0887505809
Revises: 3e87179608e3
Create Date: 2026-08-31 15:28:55.168857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0887505809'
down_revision: Union[str, None] = '3e87179608e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferencias_usuario', sa.Column('tarjetas_ocultas', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferencias_usuario', 'tarjetas_ocultas')
    # ### end Alembic commands ###
