"""checklist_multitema_notas_proyecto

Revision ID: 249ae1f20365
Revises: 08f319b66df4
Create Date: 2026-08-17 17:24:38.545521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249ae1f20365'
down_revision: Union[str, None] = '08f319b66df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Postgres no autogenera ALTER TYPE ... ADD VALUE para un enum ya
    # existente -- mismo caveat ya documentado para TipoNotificacion.reunion_hoy.
    op.execute("ALTER TYPE tipoagendaitem ADD VALUE IF NOT EXISTS 'nota'")
    op.add_column('agenda_items', sa.Column('nota_id', sa.Integer(), nullable=True))
    op.add_column('agenda_items', sa.Column('seccion_proyecto_id', sa.Integer(), nullable=True))
    op.add_column('agenda_items', sa.Column('detalle', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'agenda_items', 'notas', ['nota_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'agenda_items', 'proyectos', ['seccion_proyecto_id'], ['id'], ondelete='SET NULL')
    op.add_column('notas', sa.Column('proyecto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notas', 'proyectos', ['proyecto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notas', type_='foreignkey')
    op.drop_column('notas', 'proyecto_id')
    op.drop_constraint(None, 'agenda_items', type_='foreignkey')
    op.drop_constraint(None, 'agenda_items', type_='foreignkey')
    op.drop_column('agenda_items', 'detalle')
    op.drop_column('agenda_items', 'seccion_proyecto_id')
    op.drop_column('agenda_items', 'nota_id')
    # Nota: Postgres no soporta DROP VALUE de un enum -- el downgrade deja
    # 'nota' en el tipo tipoagendaitem aunque ya no haya filas usándolo,
    # mismo caveat que el resto de este repo con enums de Postgres.
    # ### end Alembic commands ###
