"""intentos fallidos (opcion B)

Revision ID: 3f388ed63552
Revises: 14d7abb3c7fa
Create Date: 2026-09-17 16:47:41.582407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f388ed63552'
down_revision: Union[str, None] = '14d7abb3c7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intentos_fallidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('correo_intentado', sa.String(length=150), nullable=True),
    sa.Column('metodo', sa.String(length=10), nullable=False),
    sa.Column('ruta', sa.String(length=300), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intentos_fallidos_fecha'), 'intentos_fallidos', ['fecha'], unique=False)
    op.create_index(op.f('ix_intentos_fallidos_id'), 'intentos_fallidos', ['id'], unique=False)
    # Nota: se quitó del autogenerate un drop_constraint de
    # 'suscripciones_push_endpoint_key' detectado como drift preexistente
    # en la BD, sin relación con este cambio -- no se toca aquí.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intentos_fallidos_id'), table_name='intentos_fallidos')
    op.drop_index(op.f('ix_intentos_fallidos_fecha'), table_name='intentos_fallidos')
    op.drop_table('intentos_fallidos')
    # ### end Alembic commands ###
