"""agregar ultimo_login y aviso_acceso_enviado a usuario

Revision ID: 5081d26d7d66
Revises: 2de6077619f6
Create Date: 2026-08-21 16:58:48.452890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5081d26d7d66'
down_revision: Union[str, None] = '2de6077619f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('usuarios', sa.Column('ultimo_login', sa.DateTime(), nullable=True))
    # server_default necesario (2026-08-21): la tabla usuarios ya tiene
    # filas reales -- sin un valor de respaldo, el ALTER TABLE con
    # NOT NULL fallaría al no saber qué poner en esas filas existentes.
    # Se quita el default después del backfill (mismo patrón ya usado en
    # 65db28fa8343/2de6077619f6 para 'orden') para que quede como
    # nullable=False sin default real de aquí en adelante.
    op.add_column(
        'usuarios',
        sa.Column('aviso_acceso_enviado', sa.Boolean(), server_default='false', nullable=False),
    )
    op.alter_column('usuarios', 'aviso_acceso_enviado', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'aviso_acceso_enviado')
    op.drop_column('usuarios', 'ultimo_login')
    # ### end Alembic commands ###
