"""baseline

Revision ID: 65cc6ae752b0
Revises:
Create Date: 2026-08-17 08:09:37.251996

Nota (2026-08-20): originalmente esta migracion estaba vacia (upgrade/
downgrade como "pass") porque se genero sobre una base de datos que ya
tenia el esquema completo, creado por el viejo Base.metadata.create_all().
Eso funcionaba en la Pi (la base real ya existia), pero significaba que
"alembic upgrade head" NUNCA podia levantar el esquema completo en una base
de datos vacia (confirmado al intentar levantar el proyecto en una base
nueva para un entorno de desarrollo separado). Se regenero el contenido de
esta migracion a partir del estado real de los modelos SQLAlchemy en esta
fecha (via alembic.autogenerate.produce_migrations contra una base vacia)
para que sea autosuficiente. No afecta la base real de la Pi: esa base ya
tiene todas estas tablas, así que Alembic no vuelve a ejecutar el upgrade()
de una revision ya aplicada.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cc6ae752b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('cumpleanos', 'festivo', 'evento', name='tipoeventoempresa'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'tipo', name='uq_evento_empresa_nombre_tipo')
    )
    op.create_index(op.f('ix_eventos_empresa_id'), 'eventos_empresa', ['id'], unique=False)
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyectos_id'), 'proyectos', ['id'], unique=False)
    op.create_index(op.f('ix_proyectos_parent_id'), 'proyectos', ['parent_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('puesto', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('es_super_admin', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('entregables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=False),
    sa.Column('porcentaje_avance', sa.Integer(), nullable=False),
    sa.Column('estatus', sa.Enum('pendiente', 'en_progreso', 'cumplido', name='estatusentregable'), nullable=False),
    sa.Column('sensible', sa.Boolean(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('urgente_manual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entregables_id'), 'entregables', ['id'], unique=False)
    op.create_table('equipo_miembros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propietario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('N1', 'N2', 'N3', 'N4', name='rolenum'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['propietario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('propietario_id', 'usuario_id', name='uq_equipo_propietario_usuario')
    )
    op.create_index(op.f('ix_equipo_miembros_id'), 'equipo_miembros', ['id'], unique=False)
    op.create_table('pendientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=500), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pendientes_id'), 'pendientes', ['id'], unique=False)
    op.create_table('series_reunion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('organizador_id', sa.Integer(), nullable=False),
    sa.Column('tipo_recurrencia', sa.Enum('diaria', 'semanal', 'mensual', name='tiporecurrencia'), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=True),
    sa.Column('dia_mes', sa.Integer(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organizador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_reunion_id'), 'series_reunion', ['id'], unique=False)
    op.create_table('usuario_proyecto_rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('N1', 'N2', 'N3', 'N4', name='rolenum'), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'proyecto_id', name='uq_usuario_proyecto')
    )
    op.create_index(op.f('ix_usuario_proyecto_rol_id'), 'usuario_proyecto_rol', ['id'], unique=False)
    op.create_table('historial_avance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entregable_id', sa.Integer(), nullable=False),
    sa.Column('porcentaje_avance', sa.Integer(), nullable=False),
    sa.Column('actualizado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['entregable_id'], ['entregables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_avance_id'), 'historial_avance', ['id'], unique=False)
    op.create_table('reuniones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('organizador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['serie_id'], ['series_reunion.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reuniones_id'), 'reuniones', ['id'], unique=False)
    op.create_table('serie_reunion_participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['serie_id'], ['series_reunion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serie_reunion_participantes_id'), 'serie_reunion_participantes', ['id'], unique=False)
    op.create_table('minutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reunion_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reunion_id'], ['reuniones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reunion_id')
    )
    op.create_index(op.f('ix_minutas_id'), 'minutas', ['id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('entregable_id', sa.Integer(), nullable=True),
    sa.Column('evento_empresa_id', sa.Integer(), nullable=True),
    sa.Column('reunion_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('recordatorio_proximo', 'recordatorio_vencido', 'entregable_asignado', 'avance_actualizado', 'reunion_hoy', 'otro', name='tiponotificacion'), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('urgente', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entregable_id'], ['entregables.id'], ),
    sa.ForeignKeyConstraint(['evento_empresa_id'], ['eventos_empresa.id'], ),
    sa.ForeignKeyConstraint(['reunion_id'], ['reuniones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_table('reunion_participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reunion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reunion_id'], ['reuniones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reunion_participantes_id'), 'reunion_participantes', ['id'], unique=False)
    op.create_table('acuerdos_minuta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minuta_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('entregable_id', sa.Integer(), nullable=True),
    sa.Column('convertido', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entregable_id'], ['entregables.id'], ),
    sa.ForeignKeyConstraint(['minuta_id'], ['minutas.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acuerdos_minuta_id'), 'acuerdos_minuta', ['id'], unique=False)
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entregable_id', sa.Integer(), nullable=True),
    sa.Column('reunion_id', sa.Integer(), nullable=True),
    sa.Column('minuta_id', sa.Integer(), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('nota_padre_id', sa.Integer(), nullable=True),
    sa.Column('pendiente_padre_id', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('imagen_path', sa.String(length=300), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(CASE WHEN entregable_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN reunion_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN minuta_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN proyecto_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN nota_padre_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN pendiente_padre_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_nota_exactamente_un_padre'),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['entregable_id'], ['entregables.id'], ),
    sa.ForeignKeyConstraint(['minuta_id'], ['minutas.id'], ),
    sa.ForeignKeyConstraint(['nota_padre_id'], ['notas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pendiente_padre_id'], ['pendientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['reunion_id'], ['reuniones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_id'), 'notas', ['id'], unique=False)
    op.create_table('agenda_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.Column('reunion_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('tema', 'entregable', 'acuerdo', 'pendiente', 'nota', name='tipoagendaitem'), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('entregable_id', sa.Integer(), nullable=True),
    sa.Column('acuerdo_id', sa.Integer(), nullable=True),
    sa.Column('nota_id', sa.Integer(), nullable=True),
    sa.Column('pendiente_id', sa.Integer(), nullable=True),
    sa.Column('seccion_proyecto_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.String(length=500), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en_reunion_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(CASE WHEN serie_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN reunion_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_agenda_item_serie_o_reunion'),
    sa.ForeignKeyConstraint(['acuerdo_id'], ['acuerdos_minuta.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_en_reunion_id'], ['reuniones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entregable_id'], ['entregables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nota_id'], ['notas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pendiente_id'], ['pendientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reunion_id'], ['reuniones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seccion_proyecto_id'], ['proyectos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['serie_id'], ['series_reunion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_items_id'), 'agenda_items', ['id'], unique=False)
    op.create_table('agenda_item_revisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agenda_item_id', sa.Integer(), nullable=False),
    sa.Column('reunion_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('revisado', 'pendiente', 'revisado_con_pendientes', name='estadorevision'), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['agenda_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reunion_id'], ['reuniones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_item_revisiones_id'), 'agenda_item_revisiones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agenda_item_revisiones')
    op.drop_table('agenda_items')
    op.drop_table('notas')
    op.drop_table('acuerdos_minuta')
    op.drop_table('reunion_participantes')
    op.drop_table('notificaciones')
    op.drop_table('minutas')
    op.drop_table('serie_reunion_participantes')
    op.drop_table('reuniones')
    op.drop_table('historial_avance')
    op.drop_table('usuario_proyecto_rol')
    op.drop_table('series_reunion')
    op.drop_table('pendientes')
    op.drop_table('equipo_miembros')
    op.drop_table('entregables')
    op.drop_table('usuarios')
    op.drop_table('proyectos')
    op.drop_table('eventos_empresa')
    # ### end Alembic commands ###
