"""agregar orden a proyecto

Revision ID: 65db28fa8343
Revises: 8a86ce1ef8c1
Create Date: 2026-08-19 01:46:03.126349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65db28fa8343'
down_revision: Union[str, None] = '8a86ce1ef8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: se quitó de aquí un drop_index('ix_agenda_items_tema_activo_unico')
    # que autogenerate detectó como "sobrante" -- ese índice existe en la
    # base pero no está declarado como tal en el modelo AgendaItem (se creó
    # fuera de Alembic, antes de la migración a ese sistema, ver sección 6
    # de CLAUDE.md). No es parte de este cambio (solo agrega Proyecto.orden)
    # y borrarlo de paso sería quitar una restricción de integridad real sin
    # que nadie lo haya pedido.
    op.add_column('proyectos', sa.Column('orden', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###

    # Backfill (2026-08-18): sin esto, TODOS los temas ya existentes quedan
    # empatados en orden=0 (el default) -- con todos los hermanos empatados,
    # la primera vez que alguien use la flecha ↑/↓ (mover_proyecto) el
    # intercambio de valores sería 0<->0, sin ningún cambio visible. Se
    # numeran por parent_id según su orden de creación actual (id), mismo
    # criterio que ya usan las filas nuevas (_siguiente_orden en
    # app/services/proyectos.py).
    op.execute(
        """
        UPDATE proyectos AS p
        SET orden = sub.rn
        FROM (
            SELECT id, ROW_NUMBER() OVER (
                PARTITION BY parent_id ORDER BY id
            ) - 1 AS rn
            FROM proyectos
        ) AS sub
        WHERE p.id = sub.id
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'orden')
    # ### end Alembic commands ###
