"""fecha_leida en notificaciones (acuse de vista)

Revision ID: 834cf4b59d69
Revises: 3f388ed63552
Create Date: 2026-09-17 17:39:23.780905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834cf4b59d69'
down_revision: Union[str, None] = '3f388ed63552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificaciones', sa.Column('fecha_leida', sa.DateTime(), nullable=True))
    # Nota: se quitó del autogenerate un drop_constraint de
    # 'suscripciones_push_endpoint_key' detectado como drift preexistente
    # en la BD, sin relación con este cambio -- no se toca aquí.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notificaciones', 'fecha_leida')
    # ### end Alembic commands ###
