"""hora opcional en entregable y pendiente personal

Revision ID: 91b59fc1dec1
Revises: 1b0887505809
Create Date: 2026-09-01 16:42:29.265458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b59fc1dec1'
down_revision: Union[str, None] = '1b0887505809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entregables', sa.Column('hora_entrega', sa.Time(), nullable=True))
    op.add_column('pendientes_personales', sa.Column('hora_limite', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pendientes_personales', 'hora_limite')
    op.drop_column('entregables', 'hora_entrega')
    # ### end Alembic commands ###
