"""asistente_voz_habilitado en usuarios

Revision ID: c02b12b1b486
Revises: 8cbafee39682
Create Date: 2026-09-17 11:45:34.865346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02b12b1b486'
down_revision: Union[str, None] = '8cbafee39682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Nota: se quitó del autogenerate un drop_constraint de
    # 'suscripciones_push_endpoint_key' detectado como drift preexistente
    # en la BD, sin relación con este cambio -- no se toca aquí.
    op.add_column('usuarios', sa.Column('asistente_voz_habilitado', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'asistente_voz_habilitado')
    # ### end Alembic commands ###
