"""mensajes_directos

Revision ID: c87281163a42
Revises: 834cf4b59d69
Create Date: 2026-09-18 12:43:31.078770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87281163a42'
down_revision: Union[str, None] = '834cf4b59d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensajes_directos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_leido', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_directos_id'), 'mensajes_directos', ['id'], unique=False)
    # Nota: autogenerate también detectó dos drifts SIN relación con este
    # cambio (quitar el índice único de agenda_items y el constraint de
    # suscripciones_push) -- quitados a mano, mismo criterio ya documentado
    # en CLAUDE.md para no aplicar drift ajeno en una migración de otra cosa.
    op.execute("ALTER TYPE tiponotificacion ADD VALUE IF NOT EXISTS 'mensaje_directo'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensajes_directos_id'), table_name='mensajes_directos')
    op.drop_table('mensajes_directos')
    # ### end Alembic commands ###
