"""agrega nota.imagen_path

Revision ID: e8c4dce1119c
Revises: a961f98dcbc9
Create Date: 2026-08-18 05:18:50.360410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8c4dce1119c'
down_revision: Union[str, None] = 'd81f6c3a9e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notas', sa.Column('imagen_path', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notas', 'imagen_path')
    # ### end Alembic commands ###
