"""fase2_3_reuniones_recurrentes

Revision ID: e956837b9aa5
Revises: 65cc6ae752b0
Create Date: 2026-08-17 13:30:12.903558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e956837b9aa5'
down_revision: Union[str, None] = '65cc6ae752b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reuniones', sa.Column('serie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reuniones', 'series_reunion', ['serie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reuniones', type_='foreignkey')
    op.drop_column('reuniones', 'serie_id')
    # ### end Alembic commands ###
